// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjvmfNuMwkWjbs-s3KFbIHck0kz6ovZc',
    appId: '1:911572902423:web:7d915ea75d59f27f937252',
    messagingSenderId: '911572902423',
    projectId: 'binaryteam-31798',
    authDomain: 'binaryteam-31798.firebaseapp.com',
    databaseURL: 'https://binaryteam-31798-default-rtdb.firebaseio.com',
    storageBucket: 'binaryteam-31798.appspot.com',
    measurementId: 'G-HCLKY6G5ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipmvkcu2xp0XMO2vMCrOMSrsA9rQPhrc',
    appId: '1:911572902423:android:88a59a70af1999d9937252',
    messagingSenderId: '911572902423',
    projectId: 'binaryteam-31798',
    databaseURL: 'https://binaryteam-31798-default-rtdb.firebaseio.com',
    storageBucket: 'binaryteam-31798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisd5kZlPLrMXu_gR6w6PMvrH09qmah8M',
    appId: '1:911572902423:ios:b7285a6fb9aab611937252',
    messagingSenderId: '911572902423',
    projectId: 'binaryteam-31798',
    databaseURL: 'https://binaryteam-31798-default-rtdb.firebaseio.com',
    storageBucket: 'binaryteam-31798.appspot.com',
    iosBundleId: 'com.example.frizerskiSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBisd5kZlPLrMXu_gR6w6PMvrH09qmah8M',
    appId: '1:911572902423:ios:b7285a6fb9aab611937252',
    messagingSenderId: '911572902423',
    projectId: 'binaryteam-31798',
    databaseURL: 'https://binaryteam-31798-default-rtdb.firebaseio.com',
    storageBucket: 'binaryteam-31798.appspot.com',
    iosBundleId: 'com.example.frizerskiSalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjvmfNuMwkWjbs-s3KFbIHck0kz6ovZc',
    appId: '1:911572902423:web:925ff35e3abeb2e9937252',
    messagingSenderId: '911572902423',
    projectId: 'binaryteam-31798',
    authDomain: 'binaryteam-31798.firebaseapp.com',
    databaseURL: 'https://binaryteam-31798-default-rtdb.firebaseio.com',
    storageBucket: 'binaryteam-31798.appspot.com',
    measurementId: 'G-00BS7EJTX0',
  );
}
